name: eye_challenge
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.9

  # CUDA toolkit (adjust version based on your GPU)
  - cudatoolkit=11.8
  - cuda-nvcc

  # CUDA-enabled PyTorch
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - pytorch-cuda=11.8

  # Core scientific libraries
  - numpy>=1.24.0,<2.0.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - scikit-image>=0.22.0

  # Computer vision
  - opencv>=4.8.0
  - pillow>=10.0.0

  # Data manipulation and analysis
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0

  # System and performance
  - psutil>=5.9.0
  - tqdm>=4.65.0

  # Development tools (optional)
  - jupyter
  - ipython
  - pytest>=7.4.0

  # Package manager
  - pip

  # Install packages via pip that aren't available in conda
  - pip:
    # Web framework
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - python-dotenv>=1.0.0

    # Image processing extras
    - opencv-contrib-python==4.8.1.78
    - albumentations>=1.3.0

    # Model management
    - gdown>=4.7.0
    - huggingface-hub>=0.19.0

    # Database
    - pymongo>=4.6.0

    # Additional utilities
    - requests>=2.31.0
    - aiofiles>=23.2.1
    - python-json-logger>=2.0.0
    - loguru>=0.7.0

    # Configuration and validation
    - pydantic>=2.5.0
    - environs>=10.0.0

    # Security
    - cryptography>=41.0.0
    - python-jose[cryptography]>=3.3.0

    # Performance and monitoring
    - memory-profiler>=0.61.0
    - prometheus-client>=0.19.0

    # File handling
    - python-magic>=0.4.27

    # Background processing (optional)
    - celery>=5.3.0
    - redis>=5.0.0

    # Rate limiting
    - slowapi>=0.1.8

    # Database utilities
    - alembic>=1.12.0

    # Type checking (development)
    - mypy>=1.8.0
    - types-requests>=2.31.0
    - types-Pillow>=10.0.0

    # Code formatting (development)
    - black>=23.0.0
    - flake8>=6.0.0
    - isort>=5.12.0

    # Testing utilities
    - pytest-asyncio>=0.21.0
    - httpx>=0.25.0  # For testing FastAPI

    # Documentation
    - mkdocs>=1.5.0
    - mkdocs-material>=9.0.0

# Post-installation commands (optional)
# Run these after creating the environment:
# conda activate eye_challenge
# pip install --upgrade pip
# python -c "import torch; print(f'CUDA available: {torch.cuda.is_available()}')"