name: eye_challenge
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  # CUDA-enabled PyTorch (automatically detects CUDA version)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8  # or 12.1 for newer GPUs
  # System packages best managed by conda
  - opencv
  - numpy>=1.24.0,<2.0.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - scikit-image>=0.22.0
  - pillow>=10.0.0
  - psutil>=5.9.0
  # Web framework packages via pip
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn==0.24.0
    - python-multipart==0.0.6
    - gdown>=4.7.0
    - huggingface-hub>=0.19.0
    - pymongo>=4.6.0
    - python-dotenv>=1.0.0
    - requests>=2.31.0
    - albumentations>=1.3.0