name: eyeq_cv_enhanced
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi
  - uvicorn
  - python-multipart
  - opencv
  - pymongo
  # Deep Learning
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - cpuonly  # Remove this line if you want GPU support
  # Image Processing
  - numpy=1.24.*  # Pin to 1.x for PyTorch compatibility
  - scipy
  - scikit-learn
  - scikit-image
  - pillow
  - imageio
  - albumentations
  # Utilities
  - tqdm
  - psutil
  - pip
  - pip:
    - python-jose
    - python-dotenv
    - requests
    - charset-normalizer
    - chardet
    - gdown
    - huggingface-hub
    - onnxruntime